# Generated by Django 3.0.11 on 2020-11-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='problem',
        ),
    ]
