# Generated by Django 3.1.2 on 2020-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201028_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='website',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
