# Generated by Django 3.1.2 on 2020-10-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201029_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
