# Generated by Django 3.1.2 on 2020-10-30 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribute',
            name='idea',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.idea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribute',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
