# Generated by Django 3.1.2 on 2020-11-05 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20201103_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribute',
            new_name='Contribution',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
    ]
