# Generated by Django 3.1.2 on 2020-11-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contribution_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.idea'),
        ),
    ]
