# Generated by Django 3.1.2 on 2020-11-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201106_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.idea'),
        ),
    ]
