# Generated by Django 3.0.11 on 2020-11-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comment'),
        ('core', '0019_auto_20201118_1956'),
    ]

    operations = [
    ]
