# Generated by Django 3.0.11 on 2020-11-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
