# Generated by Django 3.0.11 on 2020-11-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20201119_1637'),
        ('core', '0021_remove_profile_birth_date'),
    ]

    operations = [
    ]
