# Generated by Django 3.0.11 on 2020-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201123_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='solution',
            field=models.TextField(blank=True, default='Has no solution!'),
        ),
    ]
