# Generated by Django 3.0.11 on 2020-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201123_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='solution',
            field=models.TextField(),
        ),
    ]
