# Generated by Django 3.0.11 on 2020-11-23 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201123_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=500, unique=True),
        ),
    ]
